spring.application.name=back-visas
server.port=${PORT:8080}
mercadopago.access.token=${MERCADOPAGO_TOKEN}
front.domain=${NEXT_APP_URL}
allowed.origins=${ALLOWED_ORIGINS}
webhook.url=${WEBHOOK_URL}
mailersend.api.key=${MAILERSEND_API_KEY}
mailersend.sender=${MAILER_SENDER}
mailersend.reply.to=${MAILER_REPLY_TO}
template.id.usa=${TEMPLATE_ID_USA}
template.id.ca=${TEMPLATE_ID_CA}
template.id.eta=${TEMPLATE_ID_ETA}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.hibernate.ddl-auto=update
