spring.application.name=back-visas
server.port=8080
mercadopago.access.token=${MERCADOPAGO_TOKEN}
front.domain=${NEXT_APP_URL}
front.protocol=http
webhook.url=${WEBHOOK_URL}
mailersend.api.key=${MAILERSEND_API_KEY}
mailersend.sender=${MAILER_SENDER}
template.id=${TEMPLATE_ID}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/visas?useSSL=false&serverTimeZone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
